### ISSUE TITLE
mention this repo on your blog post and leanpub page

### ISSUE THREAD

**Issue by opcodewriter** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#1]
per title, I'm suggesting you should mention this repo on your blog post and leanpub page for visibility

**Comment by Vheissu** [comment]
Great suggestion. In the next published version you'll see this mentioned in the "Book Status" section with a link to this repo and I will update my blog post as well.

**Comment by Vheissu** [comment]
This is in the latest published release and the blog post has also been updated.
