### ISSUE TITLE
Building your first Aurelia app - github code issue on Linux

### ISSUE THREAD

**Issue by PeterWebTrax** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#107]
The first time I tried to build the code in this chapter manually, ie by copy and paste from the PDF, it failed to run, and showed a blank screen, and no error messages. I wasn't surprised, as copying text out of PDFs is always a pain.

So I downloaded the github code at https://github.com/vheissu/tweeter to check it. It also didn't run, but did show an error message in the browser, about the 'import statement in main.js' line 1 being wrong. 

I then went through the PDF process again, and this time was successful at getting the app to work.

I checked both main.js's and they were identical. I eventually compared the aurelia-project/aurelia.json file and found various differences. It looks like the github version is specific to Windows as it has lots of \*\* etc in it, whereas my generated one contains /*.

I replaced my github file with the generated one, and confirmed that the app now works.

I am developing on a Centos 7 box.

It might be worth noting this in the repository if it is likely to be a problem for anyone developing on Linux, which I assume is likely to be many of the users.

Is there a way of 'rebuilding' the app from the downloaded version, so that it converts any platform specific stuff?

And is this a generic problem with Aurelia apps, that the builds will always contain platform specific text in them.

Cheers
Pete

**Comment by Vheissu** [comment]
This is an issue that has been fixed with the CLI itself and how the paths are generated in the project file. I've got to fix up the code in the repository, but we should be good.
