### ISSUE TITLE
p2 (pdf): CoC "never really seen in the front-end framework space" ... ?

### ISSUE THREAD

**Issue by tragiclifestories** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#114]
Enjoying the book, but as an Ember fanboy, I think it's rather hard to justify this statement: 

> "Never really seen in the front-end framework space, Aurelia also takes a convention over configuration approach."

**Comment by Vheissu** [comment]
I completely agree, removed this from the book pending next release.
