### ISSUE TITLE
GistRun Examples don't Run in Chrome

### ISSUE THREAD

**Issue by boshinski** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#117]
Unfortunately the examples (like https://gist.run/?id=4fdb624dc7dd947dba143df68fdfbac9) don't seem to run in Chrome (at least Windows 7 / Chrome 54) which is my default browser.  If I copy the link to Firefox they work OK. This is probably a GistRun issue and not an issue with the examples, but I thought you'd like to know.

**Comment by Vheissu** [comment]
There appears to be an intermittent issue with Gist.run. I am looking into alternatives, thank you.
