### ISSUE TITLE
Templating->Aurelia Templating Resources->Compose clarification

### ISSUE THREAD

**Issue by wshayes** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#12]
Templating->Aurelia Templating Resources->Compose->Passing Through Data

"You can also pass through a Javascript class filename to view-model which allows you to use lifecycle methods like activate (which gets the data as its first argument as an object) inside of your ViewModel."  

Can you add an example of this?  I'm a bit confused about what you are saying here.

**Comment by Vheissu** [comment]
Nice catch, I got a bit confused reading that myself. Will definitely clarify that.
