### ISSUE TITLE
app.setRoot() usage pattern explained

### ISSUE THREAD

**Issue by wshayes** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#14]
http://patrickwalters.net/creating-multipage-apps-using-aurelia-2/

http://www.foursails.co/blog/aurelia-login-best-practices-pt-1/

Two good blogs that demonstrate using setRoot() which is handy for having multiple application shells.

I still haven't figured out the right pattern for handling having different CSS themes for different (sub)domains (e.g. allowing different companies to have different logos, theming while using the same base application).  Bonus points if you can figure out how to insert that into one of your examples.

**Comment by Vheissu** [comment]
The use of setRoot to switch between different bootstrap files is definitely a good point to make. I have noted it down.

**Comment by Vheissu** [comment]
This will be in the next book release, hopefully in a few days time.
