### ISSUE TITLE
The Skeleton Navigation Starter Application

### ISSUE THREAD

**Issue by opcodewriter** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#18]
In the book you say
"Now extract the downloaded file into your desired location. For brevity, lets extract the zip file
into either C:\aurelia-app (if you’re on Windows) or into your home directory ∼/aurelia-app
(if you’re on a Mac)."

But the skeleton .zip file has several folders 

![snip_20160303225658](https://cloud.githubusercontent.com/assets/15019084/13509275/48b7bdc2-e193-11e5-944b-56650cb0993e.jpg)

It might be useful to describe a bit what they are and what to choose

Also, you should mention that Aurelia doesn't work with Babel 6 currently.

**Comment by Vheissu** [comment]
This has been further clarified in the next release planned probably in a few days. I have added in imagery to make this part less confusing.
