### ISSUE TITLE
"Getting Up and Running / Aurelia From Scratch" issues

### ISSUE THREAD

**Issue by opcodewriter** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#19]
Issues with steps in "Aurelia From Scratch"
1. Not sure but I think it's missing gulp-notify
   I see gulpfile.js uses 'notifiy'
   so what I run  "npm install gulp-notify --save-dev"
2. After you mention the list of dev dependencies which need to be installed, it doesn't say what reader needs to to run. I assumed it's still 'gulp watch' as in the "Running The Starter Application" based on skeleton app.
3. After running 'gulp watch' if I look to dist folder, I only see 'app.html'
   Navigating to 'http://localhost:9000/' I only see "Loading..." message 
   Looking to console, it says:

> Failed to load resource: the server responded with a status of 404 (Not Found)
> Error: XHR error (404 Not Found) loading http://localhost:9000/dist/main.js(…)

**Comment by Vheissu** [comment]
For the next release I have changed the Aurelia from scratch section to address the above issues. Thanks for reporting this. I went through the process myself with the new edits to make sure things work.

**Comment by zantinger** [comment]
Got the same error as above. cmd shows following: build-system errored after xx ms, ReferenceError: to5 is not defined

**Comment by zantinger** [comment]
@Vheissu I think its a type on line 67 in gulpfile.js. seach for to5 and change it to **babel**. now it works for me
