### ISSUE TITLE
Using modernizr / polyfills to get your app to work across all browsers

### ISSUE THREAD

**Issue by VagyokC4** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#22]
Best way to detect what features you're using,
How to plug-in Modernizr for testing such features,
How to implement polyfills to fill the gaps.

**Comment by Vheissu** [comment]
I am currently writing up a big section on using polyfills, etc. It will be in the next release.

**Comment by Vheissu** [comment]
This is in chapter 2.
