### ISSUE TITLE
mention containterless and content

### ISSUE THREAD

**Issue by opcodewriter** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#23]
no mention in the book about
- `<content>`
- `@computedFrom`

generally you would expect for the book to cover everything from the Aurelia Docs plus much more (since Docs is pretty small)

I might be asking for too much maybe  :laughing:

**Comment by Vheissu** [comment]
`@computedFrom` should definitely be in there. I held off on `<content>` because that is deprecated in the official specification and will be replaced by `<slot>` I do believe. I am holding off until Aurelia adopts the newer specification tag and how it will work with the framework.

**Comment by opcodewriter** [comment]
I know it sounds like more work for you, but anyone buying the book now should know about small but very useful features `<content>` even if it's going to be changed later on 
Maybe have a list of features which you know are probably going to be modified or removed in Aurelia in the future, but until maybe mention them

**Comment by Vheissu** [comment]
Discussion of the `computedFrom` decorator will be in chapter 6. Discussion about the `<content>` element including notes on pending deprecation in favour of `<slot>` are discussed in chapter 5. This is all pending next release.
