### ISSUE TITLE
bindable attribute accepts multiple values

### ISSUE THREAD

**Issue by opcodewriter** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#24]
in "A View Without A Viewmodel (HTML Partials)" you give this example:
`<template bindable="router">`
I think it's very useful to know that you can declare multiple comma separated properties:
`<template bindable="prop1,prop2">`
`<myComponent prop1="a" prop2="b"></myComponent>`

**Comment by Vheissu** [comment]
This is in chapter 3
