### ISSUE TITLE
Add link to "Adding In Bluebird Promise Library"

### ISSUE THREAD

**Issue by opcodewriter** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#26]
Add a link to the user voice issue on Edge promise support for users to track progress (also suggest reader it can change at anytime and even they should vote for it :) )
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/11329845-improve-promise-implementation-performance

**Comment by Vheissu** [comment]
This is in chapter 2.
