### ISSUE TITLE
Consider webpack

### ISSUE THREAD

**Issue by opcodewriter** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#3]
Consider showing using webpack too. 
I heard that JSPM being really slow
http://blog.dripstat.com/why-we-switched-from-jspm-to-webpack/
Moreover please see  https://github.com/aurelia/skeleton-navigation/issues/41

**Comment by Vheissu** [comment]
At present Webpack isn't officially supported with Aurelia. When it is though, definitely worth adding into the book. So until it lands, I might hold off on this. I am yearning for Webpack support with Aurelia.

**Comment by Vheissu** [comment]
Now that there is an official solution for Webpack, I am going to update the next release with how to use it now I have played with it a little bit.

**Comment by Vheissu** [comment]
This missed out on the latest release. However next release hopefully.

**Comment by wshayes** [comment]
Some things I'm uncertain about with webpack - how to pull github/file (e.g non-npm) packages in, how to make sure CSS is loaded in the correct order, shimming modules that aren't setup correctly, where are the dragons - e.g. what problems is one likely to run into on an Aurelia project.

**Comment by Vheissu** [comment]
@wshayes There are definitely quite a few differences when it comes to using Webpack in comparison to TypeScript and Babel based on my experience changing over. I think this definitely needs to be its own section because there are a few things the user needs to know from how packages are installed and handled, working with packages that expose globals like jQuery, aliases, CSS load order and more.

**Comment by wshayes** [comment]
Really looking forward to this chapter.  I was delighted by the build performance of the webpack skeleton and ease of use.  Hoping to switch over, but I'm a bit concerned about the dragons in these uncharted waters.  Anything you can do to help would be wonderful.  Even in your chapter pointing out some of the better tutorials and documentation - though the documentation is much better than the JSPM documentation.

**Comment by Vheissu** [comment]
Touched upon Webpack in the latest release. Please let me know if I missed anything or something isn't clear, please let me know.
