### ISSUE TITLE
Recipe(s) for application exception logging

### ISSUE THREAD

**Issue by andrewransom** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#34]
It would be very useful to describe how best to do application-level logging in a consistent, best-practices way. Some bits to include/adapt:
- Describe use of the `aurelia-logging` component
- Mike O'Brien's [Client Side Exception Logging in an Aurelia Application](http://www.mikeobrien.net/blog/client-side-exception-logging-in-aurelia/) 

A more unified overview would be great!

**Comment by Vheissu** [comment]
This will be in chapter 3 of the book once new release is pushed.
