### ISSUE TITLE
CompositionTransaction - didn't know about this

### ISSUE THREAD

**Issue by wshayes** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#36]
https://github.com/aurelia/framework/issues/367#issuecomment-198104416

Kind of advanced but ...

**Comment by Vheissu** [comment]
Wow, this is really awesome. This definitely needs to be added into the book.

**Comment by MarkHerhold** [comment]
@Vheissu please check the latest comments in the other issue... enlisting in the `bind()` callback is likely a better default choice than enlisting in the constructor.

**Comment by Vheissu** [comment]
@MarkHerhold Thanks for the heads up. It seems using `bind` is definitely the way to go.

**Comment by Vheissu** [comment]
This made its way into the latest release of the book in chapter 8.
