### ISSUE TITLE
Object observation tip from jdanyow and Rob

### ISSUE THREAD

**Issue by wshayes** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#38]
https://github.com/aurelia/framework/issues/381#issuecomment-201928292

**Comment by Vheissu** [comment]
Something definitely worth adding into the object binding section. Thanks @wshayes

**Comment by wshayes** [comment]
Rob also had this tidbit which helped me as well (from view it on GitHub https://github.com/aurelia/framework/issues/367#issuecomment-202165547):

However, my personal recommendation is to not put data access inside of "widgets" but instead to put that inside "screens" that are controlled by the router. Then you can control navigation if there is a failure. Those screens can then bind the data into the widgets which encapsulate some common rendering.

**Comment by Vheissu** [comment]
This made its way into the latest release and the binding chapter 6.
