### ISSUE TITLE
Show alternate way to inject without decorator

### ISSUE THREAD

**Issue by Vheissu** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#4]
As per @wshayes suggestion in the book Disqus comments, show how to inject dependencies without needing to use the `@inject`

**Comment by Vheissu** [comment]
The alternate method of injecting dependencies without the `@inject` dependency will probably make its way into the next published release of the book in maybe a week or so.

**Comment by opcodewriter** [comment]
which chapter or page is this shown in today's update?

if it's not too much work, would be great if you mention this in all issues which get into the book. at least for those which might not be so obvious. maybe as book grows this would become of great help.
for example I searched for 'inject' and I couldn't see this new way. 
thanks a lot!

**Comment by Vheissu** [comment]
Sorry @mikefills this is an unpublished chapter on Dependency Injection. It'll probably be another release or two before it's pushed out. Sorry all of the chapters roll into one sometimes.

**Comment by Vheissu** [comment]
A WIP version of the dependency injection chapter is coming next release.

**Comment by Vheissu** [comment]
Latest release is out and this is in the dependency injection chapter 11.
