### ISSUE TITLE
description of | and &

### ISSUE THREAD

**Issue by MisterHux** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#41]
Just a suggestion (love the book so far), but when reading the valueConverters part, I had to stop reading the book to go make sure that | was really a pipe and not something else.  I would suggest putting in a part explaining all (or rather the 2 that I've seen) the different symbols that can be used in bindings and what they mean/do.

**Comment by Vheissu** [comment]
Great catch there @MisterHux I will definitely add in some further explanations and clarity of the binding language and symbols.
