### ISSUE TITLE
.call 

### ISSUE THREAD

**Issue by wshayes** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#43]
```
Essentially it passes a function reference. You can pass in a function and then call it like a standard function. If you have a custom element and you allow users to pass through functions to be called by the custom element, like a close callback or something, this is what you will use.

The call binding functionality is not intended to be used for standard browser events. It is more of allowing functions to be passed through and calling the original function by reference.
```

I still don't understand what the .call binding does and the example further down didn't clear it up.  Could you elaborate more on this?

**Comment by opcodewriter** [comment]
an example is a must have in the book.

**my-view.js** defines a `create`

```
export class MyView 
{
   @bindable create;
}
```

**my-view.html** calls `create()` 

```
<template>
   <button type="button" click.delegate="create()">Create</button>
</template>
```

**app.html** passes `create_now` to `my-view`:

```
<template>
   <my-view create.call="create_now()"></my-view>
</template>
```

**app.js**

```
export class MyView 
{
    create_now() 
    {
    }
}
```

I should had created a gist :)

**Comment by Vheissu** [comment]
I absolutely agree guys, I will definitely add in some clarification for this in the next release.

**Comment by Vheissu** [comment]
I've made your above provided example @opcodewriter into a Gist accessible [here](https://gist.github.com/Vheissu/9b49c26623f4dc6e63a0347ca48af6b3) and a Gist.run example [here](https://gist.run/?id=9b49c26623f4dc6e63a0347ca48af6b3).

**Comment by wshayes** [comment]
Ahh!  Thanks @opcodewriter - that is very clear now.
