### ISSUE TITLE
Code referred to in the book

### ISSUE THREAD

**Issue by owenellis** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#44]
I assume I am missing something really simple but am going through the Forms chapter and there is reference to code and a number of links but none of them appear to work. For example, on page 134 there is a link to code/validate-js.js but the link simply opens a browser to my default home page. Where should it be linking to? There is mention of code examples being on Github or through Leanpub but again I could not find and code related to the book.

Thanks!

**Comment by Vheissu** [comment]
@owenellis This is definitely an issue that has occurred during the publishing phase. Sorry about that. I'll get out an emergency release in an hour or so for you.

**Comment by owenellis** [comment]
Thanks so much, just glad I was not going crazy as that is always a possibility!

**Comment by Vheissu** [comment]
@owenellis I've just pushed out a new version which fixes those broken links, although you won't receive a notification, it has just been pushed out. Thank you for reporting this.

**Comment by owenellis** [comment]
Thanks for the quick response!

Really enjoying the book and finding it very useful.
