### ISSUE TITLE
Fetch chapter?

### ISSUE THREAD

**Issue by wshayes** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#45]
There are quite a few tricks associated with using Fetch - not Aurelia per se, but it's pretty much required to make a useful application.  Covering GET, POST,  file upload/download (and getting dynamic files from backend using authentication where the Content Disposition is not handled - e.g. http://www.nuxeo.com/blog/give-stuff-authenticated-file-download-in-javascript/), interceptors handling things like 401's like how the Aurelia-Authentication plugin does it,  setting connection defaults, using a singleton vs using new to create a new connection handler each time, etc.  

I just saw that there is a promise.cancel option for fetch - that's not part of the fetch API from what I can tell - would be good to talk about use of that for things like autocompletion where the requests can come back out of order leading to confusion for autocompletes

**Comment by Vheissu** [comment]
Absolutely @wshayes there will be a chapter 12 titled, "HTTP & Fetch Clients" which will touch upon Fetch and the Http client, recipes, etc.

I created this awesome structure document which should give you a good idea of what is coming down the pipe, keen to hear your input on future chapters: https://github.com/Vheissu/aurelia-for-real-world-web-applications-book-feedback/wiki/Structure

**Comment by wshayes** [comment]
Looking over your outline makes me think of only one thing - Write Faster!!!  :)  Looks great - looking forward to the additional chapters.    The only thing I could think of as an additional section is the Tips/Tricks/FAQ/Cookbook section I mentioned before.
