### ISSUE TITLE
Persisting Form Data Checkbox Example?

### ISSUE THREAD

**Issue by vimcat** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#46]
adding click.delegate to a form with a single checkbox whose value is true/false to saveField causes the checkbox to stop working.

```
formValues.myCheckbox = false;
<input type="checkbox" checked.bind="formValues.myCheckbox"  click.delegate="saveField(myCheckbox, $event.target.value)"  /> // sets the value to 'on' and checkbox stops working
<input type="checkbox" checked.bind="formValues.myCheckbox"  click.delegate="saveField(myCheckbox, !formValues.myCheckbox)"  /> // toggles T/F and checkbox stops working
```

What's the proper way to do it? Thanks!

**Comment by wshayes** [comment]
Return true from the save field method

**Comment by Vheissu** [comment]
What @wshayes said is the correct way to make the event continue, otherwise default behaviour is to prevent the default action.
