### ISSUE TITLE
When to use @inject

### ISSUE THREAD

**Issue by zantinger** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#48]
Hi, I see a lot of examples which import (i.e.) HttpClient from aurelia-http-client and then use '@inject(HttpClient)' to use http on the constructor. However at the chapter 'Creating A Server-side Log Appender' there is no inject for the HttpClient. 
I can't find any explanation on this chapter or the chapter for DI why this so is.

**Comment by opcodewriter** [comment]
I think it's just an error, it should have `@inject(HttpClient)` decorator on the class

**Comment by zantinger** [comment]
ok, that's what I thought too. Thanks

**Comment by Vheissu** [comment]
@zantinger Sorry about that, this is definitely an error. I'll get it fixed up for the next release.
