### ISSUE TITLE
Status of book

### ISSUE THREAD

**Issue by MarkBrightFutureApps** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#52]
I purchased book at 60% completion.. 
Two section I'm interested in are: 
  Porting app from Angular
  Working with the Fetch and Http Client dependencies

Any idea when these will be added?

**Comment by Vheissu** [comment]
@MarkBrightFutureApps Hopefully within the next two weeks or so mate.

Is there anything in the meantime that I can help with to answer your questions?
