### ISSUE TITLE
Node Modules in Aurelia

### ISSUE THREAD

**Issue by zantinger** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#61]
Hi. I install the Image Processing Modult Jimp in my Aurelia App. But when I import Jimp in my class I get an error. Because Aurelia is a front-end Framework, I ask myself if it is possible to have access to node modules in the backend?

**Comment by Vheissu** [comment]
A lot of Node modules will work on the client-side, but not all of them. Some require low-level access to disk and other things not available on the client side.

**Comment by zantinger** [comment]
ok, thanks
