### ISSUE TITLE
Typescript ES6 Cross-Browser Recipe

### ISSUE THREAD

**Issue by brettveenstra** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#62]
Typescript (targeting ES6 so you get clean async/await) setup that uses Bluebird that can run on Edge, IE, FF & Chrome with JSPM or WebPack

**Comment by Vheissu** [comment]
I think this is a great thing to add. There are advantages to compiling to ES6 and then using Babel as the second step.

**Comment by Vheissu** [comment]
This is what the official skeleton offers. The book will make mention of this, if this is the desired approach.
