### ISSUE TITLE
Command line examples

### ISSUE THREAD

**Issue by robbohn** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#63]
A lot of work went into this - nice job.

I would recommend **consistently** writing your command line examples as separate lines rather than embedded in the text; i.e. instead of this on page 12:

> Now we want to make sure we have the latest version of System.js, execute the command `jspm dl-loader --latest` which downloads the latest version.

I would instead recommend you do this:

> Now we want to make sure we have the latest version of System.js, execute the command
> `jspm dl-loader --latest`
> which downloads the latest version.

You do this some of the time, but not always.  I was thrown by the trailing hypen - sometimes needed in some *nix commands so I always had to _figure out_ the command to see if the hyphen was relevant to the command or was merely a separator from the later text.

Rob

**Comment by Vheissu** [comment]
@robbohn Really good point Rob. I never actually realised I was jumping between the two styles. I definitely agree standalone command line examples are best than the inline ones, especially for copying/pasting as well.
