### ISSUE TITLE
Misspelled the word "logic" in "Crash Course In Aurelia" section

### ISSUE THREAD

**Issue by jwatkin** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#66]
In "1. Crash Course In Aurelia":

"We will also be detailing how to work with Aurelia’s console loggic functionality to create your own console loggers..."

"loggic" should be spelled "logic"

Should we just assume you'll run everything through a spellchecker before the next release? Or, should we continue to report spelling errors?

Thank you for writing this book,
Jim

**Comment by Vheissu** [comment]
@jwatkin At the end of the book I will be sending the book to a firm who will be going through the book with a fine tooth comb and finding the 10 million grammatical and spelling errors. However, if you spot any obvious ones, definitely feel free to report them as they'll make it easier for current readers to read the book if it makes more sense, haha.
