### ISSUE TITLE
Style suggestion to avoid a repeated word, and to simplify

### ISSUE THREAD

**Issue by jwatkin** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#67]
In "1. Crash Course In Aurelia":

"In this chapter we are going to be going through the individual components of Aurelia."

Perhaps this could be refined to:
"In this chapter, we'll go through the individual components of Aurelia."
or
"In this chapter, we'll examine the individual components of Aurelia."

Jim

**Comment by Vheissu** [comment]
Good suggestion @jwatkin I think this wording is much nicer and definitely what I will use going forward.
