### ISSUE TITLE
Style suggestions for the feedback page

### ISSUE THREAD

**Issue by jwatkin** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#68]
(https://github.com/Vheissu/aurelia-for-real-world-web-applications-book-feedback)

In "Spelling and Grammar":
"At present, the book is in a raw and constantly in progress state."
Maybe this would sound better:
"At present, the book is in a raw state."
Or
"At present, the book is a work in progress and is still raw."

In "Chapter/Content Suggestions"
"If you had any ideas for subject content in the book, definitely let me know."
Should be:
"If you **have** any ideas for subject content in the book, definitely let me know."

**Comment by Vheissu** [comment]
Thanks @jwatkin just made those changes, good stuff.
