### ISSUE TITLE
Suggestion: Extend Application Structure to include CSS

### ISSUE THREAD

**Issue by go4cas** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#70]
Great book so far!

The chapter "**Structuring Your Aurelia Applications**" is really helpful. I would like to see the following additions to this chapter:
1. The one aspect that I'm missing here is some guidance on how to structure your stylesheets for individual custom elements, for features and common styles in one application. Example: if I build 100's of small custom elements, each with it's on styles, where would these .CSS files live? If My elements in a single feature have some common styles, where would the feature's common CSS file live? etc, etc
2. If you follow one of the deep modular strategies (e.g. strategy 4), how would you reference the different modules (e.g. custom elements of a feature, CSS of an element, etc) throughout the app, e.g. relative paths in main.js, or when you import one module in another, etc.

**Comment by Vheissu** [comment]
Great ideas, I definitely have a preferred approach for CSS in my application structure.
