### ISSUE TITLE
Errors when create a new setup from scratch with existing package.json

### ISSUE THREAD

**Issue by zantinger** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#71]
Hi. I have follow your instruction for creating aurelia from scratch. This works fine. But how do I clone this setup to make a new project without making all the steps again and again. I took the package.json, config.js, gulpfile.js, index.html and the jspm and src folder to a new directory. When I run jspm install or npm install I get errors on some packages. And when I run gulp watch the response is: gulp is not found.

**Comment by Vheissu** [comment]
Gulp needs to be installed globally on your machine for it to work. I must have forgotten to add this into the book.
