### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by kabaehr** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#76]
On Page 39:

> (unless you try and access the element itself from within a
> **viwmodel**)

**Comment by kabaehr** [comment]
On page 113:

> **Thorugh** the use of option attributes, we can allow an attribute to
> support multiple values

**Comment by kabaehr** [comment]
Page 119:

> Or better yet, if you just want to **speciy** a different view

**Comment by Vheissu** [comment]
Great feedback, I'll get these fixed up for the next release. Thank you.
