### ISSUE TITLE
(Conventionless) Custom Element

### ISSUE THREAD

**Issue by andrewflierman** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#81]
In the chapter Custom Elements you suppply code examples for creating custom elements. 
Personally I find it useful to see the implementation as well in a html example :smile: But that is a minor thing. 

One thing I don't understand from the text or code example is why your using `aurelia-pal`? 
Currently using your code example gives me Di errors: 

`Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?`

Without aurelia-pal it is working. What is the meaning of aurelia-pal to the concept of (conventionless) custom element?

**Comment by Vheissu** [comment]
The Aurelia Pal library is just an environment specific library for working with browser API's and DOM. The Element you speak of is a native definition. I need to update this in the book though to address new changes to Aurelia.
