### ISSUE TITLE
Code snippets syntax

### ISSUE THREAD

**Issue by maximusmusterus1** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#82]
I just started reading your book and I really like it and appreciate your work!

In chapter 3 some of your JS code snippets have a weird syntax (e. g. page 32, 35, 36, 37, 41, …) like
`src/user.js {lang="js"} "' export class User { …`
and I personally think that this makes them harder to read. I don't know if this is on purpose or that some formatting gone wrong, but I hope you might change it. :)

Keep up the good work!

**Comment by Vheissu** [comment]
This appears to be an issue with how the code examples are being parsed by Leanpub. I'll have a look at this though, because this is definitely formatting gone wrong. Thanks for letting me know!
