### ISSUE TITLE
Aurelia-pal

### ISSUE THREAD

**Issue by dukabcn** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#84]
Hi!

I have bought your book recently and it has been great to understand the concepts behind Aurelia. I need a clarification, though. In chapter 2, section "Browser Detection", you explain how to install and use the "Aurelia-pal" module by running a jspm command and then by declaring it in the code.  In which file do I need to import Aurelia-pal into?

Best regards,
Pedro

**Comment by Vheissu** [comment]
This is addressed in the upcoming release. Thanks for taking the time to create this issue.
