### ISSUE TITLE
Possible typo / page 19

### ISSUE THREAD

**Issue by dukabcn** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#85]
Hi!

On page 19, chapter 2, section "Caveats", you have written "you can however working around this by manually loading". I think the correct sentence should be "you can however work around this by manually loading".

I am not 100% sure about this as I am not a native English speaker. Still, I think I should point it out in case it is a typo.

Cheers

**Comment by Vheissu** [comment]
Thanks @dukabcn this is definitely a typo. Will get this out for the next release.
