### ISSUE TITLE
Add in simple example application for a report builder showing widget system and ability to add in widget components

### ISSUE THREAD

**Issue by Vheissu** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#9]
A suggestion received by a reader on Gitter. They want to know how to build a builder type application where you can drag in components, etc. This was a suggestion from @tosso

**Comment by wshayes** [comment]
Example blog article on this: http://www.sitepoint.com/composition-aurelia-report-builder/  

The compose and custom element features of Aurelia seem perfectly designed to create a personalized Dashboard app (e.g. Google Gadgets) where you can drag Dashboard Gadgets onto your Dashboard (weather, company phone directory, office supply ordering tool, etc).

**Comment by tosso** [comment]
I've read that too but the comment in article states it might not be the prefer way to do UI composition.

**Comment by wshayes** [comment]
Agree with the commenter as well and understand Vildan's point in trying to make it less confusing by focusing on composition, but the toolbox and report are definitely a use case for compose.  The other parts of the app should be custom elements.

**Comment by Vheissu** [comment]
Parking this for now. There will be far better examples in the applications section soon.
