### ISSUE TITLE
Add in chapter on working with modern Javascript

### ISSUE THREAD

**Issue by Vheissu** [Vheissu/aurelia-for-real-world-web-applications-book-feedback#97]
The book currently does a poor job explaining concepts like decorators, promises, classes, constants, let, spread operators and so on. Concepts used heavily in an Aurelia application. We need a chapter on this for newcomers to ES2015/ES2016 and Javascript in general.

**Comment by omidh28** [comment]
Great idea,  especially about decorators. Readers might easily google other concepts, But the resources around understanding and using decorators are very very limited and I personally suggest you to give it special attention.
I have some questions about them which might be helpful. What are they? How to use them? Can I make my own decorator and use it in Aurelia? Is it possible to avoid them? And if it is, How?
